name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2885ab3682b6cccf8998d8296590b47276d1df11055af804e2caa030103942e"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
