name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "623190831dc8426c3dafcecc699f76ffb36948eafacab26cdb78e7a26f5bc95b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
