name = "QUTMC Quick"
author = "ZekeZDev"
version = "1.0.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3af8d1e434f07adcb0cc209273b93438a885a0eb9ca70eff610e2efbc99321d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
