name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91d1d1e2504bc8abcfc6784998730a3ff753774136d73aa2c526a8269a1278aa"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
