name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be49114ad206119519946a17b1bb4855dd6b0ab9937f484248287319eeeea5b1"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
