name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91534350c7371dfdc8e195660e8b5e4b34f322ffc95974b1fabd6be29d748bbd"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
