name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed10a4572ae142091ecede11838a723a196532cc20eb6045cb27763bd74a46e6"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
