name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f7cbeb88097c42d90122442e93bf9f36f1caf3f50e5dde949ec489c0e9a22ce"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
