name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39d64ad8a33235a870669abaad9312f638a045bf3d14b5c37908331abb710502"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
