name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "323bc3de032248f199c757085a7e5f7219fd7aef39e6d52f666c95b74ed22404"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
