name = "Additive"
author = "SkywardMC"
version = "1.35.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "710722065e50f61a027663888959f5b2a9e3ce032b70de12cffc2d3451ad200b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
