name = "QUTMC Quick"
author = "ZekeZDev"
version = "1.1.0+1.21.7.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5477eec84f8a6a985bd5fee922b8840aefd2cbfd8b5fb7f7126eaa52c48cb18"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
